# Generated by Django 5.2.7 on 2025-10-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('boisson', 'Boisson Gazeuse'), ('biere', 'Bière'), ('eau', 'Eau'), ('sucrerie', 'Sucrerie')], max_length=20)),
                ('casier_contenu', models.IntegerField(choices=[(6, '6 bouteilles'), (12, '12 bouteilles'), (20, '20 bouteilles'), (24, '24 bouteilles')])),
                ('prix_achat_casier', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_vente_casier', models.DecimalField(decimal_places=0, max_digits=10)),
                ('seuil_alerte', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite_casiers', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_depot.fournisseur')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_depot.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(choices=[(1.0, 'Casier complet'), (0.75, '3/4 de casier'), (0.5, 'Demi-casier'), (0.25, '1/4 de casier')], decimal_places=2, max_digits=3)),
                ('quantite_casiers', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('est_credit', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_depot.produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
