# Generated by Django 5.2.8 on 2025-11-10 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_depot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('client_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('type_paiement', models.CharField(choices=[('especes', 'Espèces'), ('credit', 'Crédit')], max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validée'), ('annule', 'Annulée')], default='valide', max_length=20)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(choices=[(1.0, 'Casier complet'), (0.75, '3/4 de casier'), (0.5, 'Demi-casier'), (0.25, '1/4 de casier')], decimal_places=2, max_digits=3)),
                ('quantite_casiers', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_depot.bonvente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_depot.produit')),
            ],
        ),
        migrations.AddField(
            model_name='mouvement',
            name='ligne_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_depot.lignevente'),
        ),
    ]
