# Generated by Django 5.2.8 on 2025-11-16 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_depot', '0002_bonvente_lignevente_mouvement_ligne_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='bonvente',
            name='client_nom',
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='fraction',
            field=models.DecimalField(choices=[(1.0, 'Casier complet'), (0.75, '3/4 de casier'), (0.5, 'Demi-casier'), (0.25, '1/4 de casier')], decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.25)]),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite_casiers',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='quantite_casiers',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat_casier',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_casier',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bonvente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_depot.client'),
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
