# Generated by Django 5.2.8 on 2025-11-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_depot', '0004_bonlivraison_lignelivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignelivraison',
            name='casier_contenu',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='lignelivraison',
            name='prix_achat_casier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
