# Generated by Django 5.2.8 on 2025-12-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_depot', '0006_profilutilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilutilisateur',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
