# Generated by Django 5.2.8 on 2025-12-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_depot', '0007_rename_utilisateur_profilutilisateur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='carte_id_recto',
            field=models.ImageField(blank=True, null=True, upload_to='cartes_id/recto/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='carte_id_verso',
            field=models.ImageField(blank=True, null=True, upload_to='cartes_id/verso/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='statut_marital',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf(ve)')], max_length=20, null=True),
        ),
    ]
