# Generated by Django 5.2.8 on 2025-12-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_depot', '0008_profilutilisateur_carte_id_recto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonvente',
            name='date_facture_generee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonvente',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
    ]
