# Generated by Django 5.2.8 on 2026-08-02 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0010_useractionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonlivraison",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion_depot.fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="bonlivraison",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bonvente",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("valide", "Validée"),
                    ("annule", "Annulée"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bonvente",
            name="vendeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="produit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("prix_vente_casier__gte", models.F("prix_achat_casier"))
                ),
                name="prix_vente_superieur_achat",
            ),
        ),
    ]
