# Generated by Django 5.2.8 on 2026-08-02 16:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0011_alter_bonlivraison_fournisseur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lignevente",
            name="fraction",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.25")),
                    django.core.validators.MaxValueValidator(Decimal("9.99")),
                ],
            ),
        ),
    ]
