# Generated by Django 5.2.8 on 2026-08-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0012_alter_lignevente_fraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="CasierEmporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_casiers", models.IntegerField()),
                ("nombre_rendus", models.IntegerField(default=0)),
                ("date_emport", models.DateTimeField(auto_now_add=True)),
                ("date_retour_complet", models.DateTimeField(blank=True, null=True)),
                (
                    "bon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casier_emporte",
                        to="gestion_depot.bonvente",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_depot.client",
                    ),
                ),
            ],
        ),
    ]
