# Generated by Django 5.2.8 on 2026-08-02 19:56

from django.db import migrations, models


def backfill_produit_modele(apps, schema_editor):
    Produit = apps.get_model('gestion_depot', 'Produit')
    mapping = {12: 'GM12', 20: 'GM20', 24: 'PM24'}
    for produit in Produit.objects.all():
        produit.modele = mapping.get(produit.casier_contenu, 'GM12')
        produit.save(update_fields=['modele'])


def backfill_casier_modele(apps, schema_editor):
    CasierEmporte = apps.get_model('gestion_depot', 'CasierEmporte')
    for casier in CasierEmporte.objects.select_related('bon').all():
        ligne = casier.bon.lignes.select_related('produit').first()
        casier.modele = ligne.produit.modele if ligne else 'GM12'
        casier.save(update_fields=['modele'])


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0013_parametre_casieremporte"),
    ]

    operations = [
        migrations.AddField(
            model_name="casieremporte",
            name="modele",
            field=models.CharField(
                choices=[
                    ("GM12", "Grand modèle - 12 bouteilles"),
                    ("GM20", "Grand modèle - 20 bouteilles"),
                    ("PM24", "Petit modèle - 24 bouteilles"),
                ],
                default="GM12",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="modele",
            field=models.CharField(
                choices=[
                    ("GM12", "Grand modèle - 12 bouteilles"),
                    ("GM20", "Grand modèle - 20 bouteilles"),
                    ("PM24", "Petit modèle - 24 bouteilles"),
                ],
                default="GM12",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_produit_modele, migrations.RunPython.noop),
        migrations.RunPython(backfill_casier_modele, migrations.RunPython.noop),
    ]
