# Generated by Django 5.2.8 on 2026-08-02 20:23

import re
from django.db import migrations, models

CATEGORIES_AVEC_CASIERS = {'boisson', 'biere'}
SEUIL_GRAND_MODELE_CL = 50
BOUTEILLES_PAR_MODELE = {'GM12': 12, 'GM20': 20, 'PM24': 24}


def _capacite_cl(nom):
    m = re.search(r'([\d.,]+)\s*(ml|cl|l)', nom or '', re.IGNORECASE)
    if not m:
        return None
    try:
        valeur = float(m.group(1).replace(',', '.'))
    except ValueError:
        return None
    unite = m.group(2).lower()
    if unite == 'ml':
        return valeur / 10
    if unite == 'l':
        return valeur * 100
    return valeur


def _modele_auto(categorie, nom, casier_contenu):
    if categorie not in CATEGORIES_AVEC_CASIERS:
        return 'NC'
    capacite = _capacite_cl(nom)
    if capacite is not None and capacite < SEUIL_GRAND_MODELE_CL:
        return 'PM24'
    return 'GM12' if casier_contenu == 12 else 'GM20'


def backfill_produit_modele(apps, schema_editor):
    Produit = apps.get_model('gestion_depot', 'Produit')
    for produit in Produit.objects.all():
        produit.modele = _modele_auto(produit.categorie, produit.nom, produit.casier_contenu)
        produit.save(update_fields=['modele'])


def backfill_casier_bouteilles(apps, schema_editor):
    CasierEmporte = apps.get_model('gestion_depot', 'CasierEmporte')
    for casier in CasierEmporte.objects.select_related('bon').all():
        ligne = casier.bon.lignes.select_related('produit').first()
        if ligne:
            bouteilles = ligne.produit.casier_contenu
        else:
            bouteilles = BOUTEILLES_PAR_MODELE.get(casier.modele, 12)
        casier.bouteilles_par_casier = bouteilles
        casier.save(update_fields=['bouteilles_par_casier'])


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0014_casieremporte_modele_produit_modele"),
    ]

    operations = [
        migrations.AddField(
            model_name="casieremporte",
            name="bouteilles_par_casier",
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="casieremporte",
            name="modele",
            field=models.CharField(
                choices=[
                    ("GM12", "Grand modèle - 12 bouteilles"),
                    ("GM20", "Grand modèle - 20 bouteilles"),
                    ("PM24", "Petit modèle - 24 bouteilles"),
                    ("NC", "Pas de casier"),
                ],
                default="GM12",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="modele",
            field=models.CharField(
                choices=[
                    ("GM12", "Grand modèle - 12 bouteilles"),
                    ("GM20", "Grand modèle - 20 bouteilles"),
                    ("PM24", "Petit modèle - 24 bouteilles"),
                    ("NC", "Pas de casier"),
                ],
                default="GM12",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_produit_modele, migrations.RunPython.noop),
        migrations.RunPython(backfill_casier_bouteilles, migrations.RunPython.noop),
    ]
