# Generated by Django 5.2.14 on 2026-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0015_casieremporte_bouteilles_par_casier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametresEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="DEIVA", max_length=100)),
                (
                    "sous_titre",
                    models.CharField(
                        blank=True, default="Commerce Général", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Vente en Gros et en Détails de Boissons,\nEaux Minérales et Divers",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default="+22890695391 / 98888642", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="etsdeivtg@gmail.com", max_length=254
                    ),
                ),
                (
                    "adresse",
                    models.CharField(blank=True, default="Lomé - TOGO", max_length=255),
                ),
                ("devise", models.CharField(blank=True, default="F", max_length=10)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="entreprise/"),
                ),
                (
                    "cachet",
                    models.ImageField(blank=True, null=True, upload_to="entreprise/"),
                ),
                (
                    "fond_login",
                    models.ImageField(blank=True, null=True, upload_to="entreprise/"),
                ),
            ],
        ),
    ]
