# Generated by Django 5.2.8 on 2026-08-08 20:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0017_seed_parametres_entreprise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractionlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="bonvente",
            name="motif_annulation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="pourcentage_prix_vente",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                help_text="Pourcentage de majoration appliqué sur le prix d'achat pour calculer le prix de vente.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="useractionlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractionlog",
            name="module",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="produit",
            name="casier_contenu",
            field=models.IntegerField(
                choices=[
                    (6, "6 bouteilles"),
                    (12, "12 bouteilles"),
                    (15, "15 bouteilles"),
                    (16, "16 bouteilles"),
                    (20, "20 bouteilles"),
                    (24, "24 bouteilles"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("boisson", "Boisson Gazeuse"),
                    ("biere", "Bière"),
                    ("eau", "Eau"),
                    ("sucrerie", "Sucrerie"),
                    ("canette", "Canette"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_achat_casier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_vente_casier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
