# Generated by Django 5.2.8 on 2026-08-25 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0018_alter_useractionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casieremporte",
            name="facturation_par_bouteille",
            field=models.BooleanField(
                default=False,
                help_text="True si le délai de 3 jours est dépassé et la facturation passe au tarif par bouteille.",
            ),
        ),
        migrations.AddField(
            model_name="casieremporte",
            name="montant_supplementaire",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Montant supplémentaire facturé par bouteille pour les casiers non retournés à temps.",
                max_digits=12,
            ),
        ),
    ]
