# Generated by Django 5.2.8 on 2026-08-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0019_casier_emporte_facturation_bouteille"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casieremporte",
            name="facturation_par_bouteille",
        ),
        migrations.RemoveField(
            model_name="casieremporte",
            name="montant_supplementaire",
        ),
    ]
