# Generated by Django 5.2.8 on 2026-09-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_depot", "0022_lignevente_modele_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casieremporte",
            name="modele",
            field=models.CharField(
                choices=[
                    ("GM12", "Grand modèle - 12 bouteilles"),
                    ("GM20", "Grand modèle - 20 bouteilles"),
                    ("PM24", "Petit modèle - 24 bouteilles"),
                    ("EMB", "Emballage"),
                    ("NC", "Pas de casier"),
                ],
                default="GM12",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="modele",
            field=models.CharField(
                choices=[
                    ("GM12", "Grand modèle - 12 bouteilles"),
                    ("GM20", "Grand modèle - 20 bouteilles"),
                    ("PM24", "Petit modèle - 24 bouteilles"),
                    ("EMB", "Emballage"),
                    ("NC", "Pas de casier"),
                ],
                default="GM12",
                max_length=10,
            ),
        ),
    ]
