"""
Django settings for deiva_gestion project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import socket
from pathlib import Path
from decouple import config
from django.db.backends.signals import connection_created
from django.dispatch import receiver

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _ip_lan_principale():
    """Détecte l'adresse IP locale (réseau) de la machine, sans trafic externe."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        return None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-placeholder-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Nettoyage robuste des ALLOWED_HOSTS (ignorer les entrées vides / espaces)
ALLOWED_HOSTS = [
    h.strip().lower()
    for h in config('ALLOWED_HOSTS', default='localhost').split(',')
    if h.strip()
]

# Toujours accepter la boucle locale (http://127.0.0.1)…
for _host_loop in ('localhost', '127.0.0.1'):
    if _host_loop not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host_loop)

# …ainsi que l'adresse IP du réseau local de la machine : ainsi tous les
# appareils du WLAN/LAN peuvent accéder à l'application après le déploiement
# sans avoir à éditer le fichier .env (pratique pour une copie portable).
_ip_lan = _ip_lan_principale()
if _ip_lan and _ip_lan not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_ip_lan)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'crispy_forms',
    'crispy_tailwind',
    'rest_framework',
    'gestion_depot',
]

CRISPY_TEMPLATE_PACK = 'tailwind'
CRISPY_ALLOWED_TEMPLATE_PACKS = ('tailwind',)


# Planifier le rapport à 23h59 chaque jour.
# NOTE : django-crontab nécessite un démon cron (hôte ou conteneur).
# En Docker, exécuter le conteneur avec le service cron, ou utiliser celery beat.
CRONJOBS = [
    ('59 23 * * *', 'gestion_depot.management.commands.generer_rapport_quotidien.Command'),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deiva_gestion.urls'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'  

# settings.py
LOGOUT_URL = '/logout/'
LOGOUT_REDIRECT_URL = 'login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion_depot.context_processors.user_role',
                'gestion_depot.context_processors.entreprise',
            ],
        },
    },
]

WSGI_APPLICATION = 'deiva_gestion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Sélection du moteur via la variable d'environnement DB_ENGINE :
#   - 'sqlite'   (défaut en développement local, aucune variable requise)
#   - 'postgres' (production / Docker)
# Rétrocompatibilité : si DOCKER_ENV est défini, on retombe sur postgres.
DB_ENGINE = config('DB_ENGINE', default='postgres' if os.getenv('DOCKER_ENV') else 'sqlite')

if DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='db'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# SQLite : mode WAL + délai d'attente pour supporter plusieurs personnes qui
# écrivent en même temps (sinon erreur « database is locked »). Sans effet en
# PostgreSQL.
@receiver(connection_created)
def _prepare_sqlite_connexion(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        with connection.cursor() as cur:
            cur.execute('PRAGMA journal_mode=WAL;')
            cur.execute('PRAGMA busy_timeout=5000;')
            cur.execute('PRAGMA synchronous=NORMAL;')
            cur.execute('PRAGMA foreign_keys=ON;')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_TZ = True


# Servir les fichiers statiques avec Whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Important : indique où trouver les fichiers statiques

]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# À la fin de settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#MEDIA_ROOT = BASE_DIR / 'media'


# === Limites des uploads (sécurité) ===
# Taille maximale du corps d'une requête (formulaires multi-part) : 5 Mo
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
# Taille maximale d'un fichier uploadé en mémoire : 5 Mo
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024



# settings.py

# === Configuration SMTP (Gmail) ===
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)


# === Security settings (production only) ===
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# Activer uniquement si un proxy terminant le TLS (nginx/traefik/caddy) est en place.
# Pour une exposition directe HTTP (LAN), laisser False.
USE_HTTPS = config('USE_HTTPS', default=False, cast=bool)
if USE_HTTPS:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF : bloquer les origines tierces via le header Origin.
# http pour le LAN local, https si un proxy TLS est en place.
CSRF_TRUSTED_ORIGINS = []
for _host_csrf in ALLOWED_HOSTS:
    if _host_csrf in {'localhost', '127.0.0.1', '0.0.0.0'} or _host_csrf == '*':
        continue
    CSRF_TRUSTED_ORIGINS.append(f'http://{_host_csrf}')
    CSRF_TRUSTED_ORIGINS.append(f'http://{_host_csrf}:8000')
    if USE_HTTPS:
        CSRF_TRUSTED_ORIGINS.append(f'https://{_host_csrf}')
        CSRF_TRUSTED_ORIGINS.append(f'https://{_host_csrf}:8000')